const SUPA='https://twbduhmibbotregdxlla.supabase.co';
const KEY='sb_publishable_R3-rucNypGm1DPd4LHV-0A_wIoT0jBS';
const STORE='bbb_admin_session_v1';
let authMode='login',session=null,board=[],profileMap=new Map(),rankPage=0,playerPage=0;
const PAGE=50;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>v==null||v===''?null:Number(v);
const healthy=s=>!s||String(s).trim()===''||String(s).trim().toLowerCase()==='healthy';
function msg(t,ok=false){$('#authMessage').textContent=t||'';$('#authMessage').style.color=ok?'#69d99d':'#ef8585'}
function saveSession(x){session=x;localStorage.setItem(STORE,JSON.stringify(x))}
function clearSession(){session=null;localStorage.removeItem(STORE)}
function authHeaders(extra={}){return {apikey:KEY,Authorization:`Bearer ${session?.access_token||''}`,...extra}}
async function jsonFetch(url,opt={}){const r=await fetch(url,opt);let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.error||`Request failed (${r.status})`);return data}
async function refreshSession(){if(!session?.refresh_token)return false;try{const x=await jsonFetch(`${SUPA}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});saveSession(x);return true}catch{clearSession();return false}}
async function rest(path,opt={}){if(session?.expires_at&&Date.now()/1000>session.expires_at-60)await refreshSession();const headers=authHeaders(opt.headers||{});let r=await fetch(`${SUPA}/rest/v1/${path}`,{...opt,headers});if(r.status===401&&await refreshSession())r=await fetch(`${SUPA}/rest/v1/${path}`,{...opt,headers:authHeaders(opt.headers||{})});let data=null;const txt=await r.text();if(txt)try{data=JSON.parse(txt)}catch{data=txt}if(!r.ok)throw new Error(data?.message||data?.hint||`Database request failed (${r.status})`);return data}
async function rpc(name,body){return rest(`rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function checkAdmin(){const email=session?.user?.email;if(!email)return null;const rows=await rest(`bbb_admin_users?select=email,role,active&email=eq.${encodeURIComponent(email)}`);return rows?.[0]||null}
function sessionFromAuth(x){if(!x?.access_token)return null;return {...x,expires_at:Math.floor(Date.now()/1000)+(x.expires_in||3600)}}
async function signIn(email,password){const x=await jsonFetch(`${SUPA}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});saveSession(sessionFromAuth(x));const admin=await checkAdmin();if(!admin){clearSession();throw new Error('This account is authenticated but is not approved for BBB Admin.')}return admin}
async function signUp(email,password){const x=await jsonFetch(`${SUPA}/auth/v1/signup`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(x?.access_token){saveSession(sessionFromAuth(x));const admin=await checkAdmin();if(!admin){clearSession();throw new Error('Account created, but this email is not approved for BBB Admin.')}return {admin,confirmed:true}}return {confirmed:false}}
function showLogin(){ $('#loginView').classList.remove('hide');$('#appView').classList.add('hide') }
function showApp(admin){$('#loginView').classList.add('hide');$('#appView').classList.remove('hide');$('#adminRole').textContent=`${String(admin.role||'admin').toUpperCase()} ACCESS`}
async function boot(){let raw=localStorage.getItem(STORE);if(raw)try{session=JSON.parse(raw)}catch{}if(!session){showLogin();return}if(session.expires_at&&Date.now()/1000>session.expires_at-60&&!await refreshSession()){showLogin();return}try{const admin=await checkAdmin();if(!admin){clearSession();showLogin();return}showApp(admin);await loadAll()}catch(e){console.error(e);clearSession();showLogin()}}
async function loadAll(){await Promise.all([loadBoard(),loadProfiles(),loadCounts(),loadActivity()]);renderRankings();renderPlayers()}
async function loadBoard(){board=await rest('site_dynasty?select=rank,player_key,name,pos,pr,team,age,draft,market,gap,view,injury_status,injury_note,injury_updated,college,overview&order=rank.asc')||[]}
async function loadProfiles(){const rows=await rest('site_profiles?select=player_key,name,pos,team,age,draft_year,college,overall_breakdown,injury_status,injury_note,injury_updated&order=name.asc')||[];profileMap=new Map(rows.map(x=>[x.player_key,x]))}
async function loadCounts(){const [r,p]=await Promise.all([rest('site_rookies?select=player_key'),rest('site_prospects?select=player_key')]);$('#metricPlayers').textContent=board.length;$('#metricRookies').textContent=r?.length??'—';$('#metricProspects').textContent=p?.length??'—';$('#metricInjuries').textContent=board.filter(x=>!healthy(x.injury_status)).length}
function activitySummary(a){const old=a.old_row||{},neu=a.new_row||{};if(a.table_name==='dynasty_rankings'&&old.overall_rank!==neu.overall_rank)return `Rank ${old.overall_rank??'—'} → ${neu.overall_rank??'—'}`;if(a.table_name==='players')return neu.name||old.name||a.row_key;if(a.table_name==='player_profiles')return `Profile ${a.operation.toLowerCase()}`;return a.row_key||'Row changed'}
async function loadActivity(){try{const rows=await rpc('admin_recent_activity',{p_limit:20})||[];$('#activityList').innerHTML=rows.length?rows.map(a=>`<div class="activity-row"><span>${new Date(a.changed_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span><span class="activity-table">${esc(a.table_name)}</span><span class="activity-op">${esc(a.operation)}</span><span class="activity-key">${esc(activitySummary(a))}</span></div>`).join(''):'<div class="empty">No recent changes yet.</div>'}catch(e){$('#activityList').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function marketKind(x){const s=String(x.view||'').toUpperCase();if(s.includes('BUY'))return'BUY';if(s.includes('FADE'))return'FADE';return'MARKET'}
function filteredRank(){const q=$('#rankSearch').value.trim().toLowerCase(),pos=$('#rankPos').value,m=$('#rankMarket').value;return board.filter(x=>(pos==='ALL'||x.pos===pos)&&(m==='ALL'||marketKind(x)===m)&&(!q||`${x.name} ${x.team} ${x.college||''}`.toLowerCase().includes(q)))}
function renderRankings(){const list=filteredRank();const max=Math.max(0,Math.ceil(list.length/PAGE)-1);rankPage=Math.min(rankPage,max);const rows=list.slice(rankPage*PAGE,(rankPage+1)*PAGE);$('#rankBody').innerHTML=rows.map(x=>`<tr><td class="rank-number">${x.rank}</td><td class="player-name">${esc(x.name)}</td><td><span class="pos">${esc(x.pos)}</span></td><td>${esc(x.team||'—')}</td><td>${x.market?`#${x.market}`:'UR'}</td><td class="${x.gap>0?'green':x.gap<0?'red':''}">${x.gap==null?'—':(x.gap>0?'+':'')+x.gap}</td><td><div class="move-wrap"><input class="rank-input" type="number" min="1" max="${board.length}" value="${x.rank}" data-move-input="${esc(x.player_key)}"><button class="move-btn" data-move="${esc(x.player_key)}">MOVE</button></div></td><td><button class="edit-btn" data-edit="${esc(x.player_key)}">EDIT</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No players match.</td></tr>';$('#rankCount').textContent=`${list.length?rankPage*PAGE+1:0}–${Math.min((rankPage+1)*PAGE,list.length)} of ${list.length}`;$('#rankPrev').disabled=rankPage===0;$('#rankNext').disabled=rankPage>=max;bindRows()}
function filteredPlayers(){const q=$('#playerAdminSearch').value.trim().toLowerCase(),pos=$('#playerAdminPos').value,inj=$('#playerAdminInjury').value;return board.filter(x=>(pos==='ALL'||x.pos===pos)&&(inj==='ALL'||(inj==='HEALTHY'?healthy(x.injury_status):!healthy(x.injury_status)))&&(!q||`${x.name} ${x.team} ${x.college||''}`.toLowerCase().includes(q)))}
function renderPlayers(){const list=filteredPlayers();const max=Math.max(0,Math.ceil(list.length/PAGE)-1);playerPage=Math.min(playerPage,max);const rows=list.slice(playerPage*PAGE,(playerPage+1)*PAGE);$('#playerAdminBody').innerHTML=rows.map(x=>`<tr><td class="rank-number">${x.rank}</td><td class="player-name">${esc(x.name)}</td><td><span class="pos">${esc(x.pos)}</span></td><td>${esc(x.team||'—')}</td><td>${x.age??'—'}</td><td>${esc(x.college||'—')}</td><td class="${healthy(x.injury_status)?'green':'red'}">${esc(x.injury_status||'Healthy')}</td><td><button class="edit-btn" data-edit="${esc(x.player_key)}">EDIT</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No players match.</td></tr>';$('#playerAdminCount').textContent=`${list.length?playerPage*PAGE+1:0}–${Math.min((playerPage+1)*PAGE,list.length)} of ${list.length}`;$('#playerAdminPrev').disabled=playerPage===0;$('#playerAdminNext').disabled=playerPage>=max;bindRows()}
function bindRows(){$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));$$('[data-move]').forEach(b=>b.onclick=()=>movePlayer(b.dataset.move))}
async function movePlayer(key){const x=board.find(p=>p.player_key===key);const input=$(`[data-move-input="${CSS.escape(key)}"]`);const nr=Number(input?.value);if(!x||!Number.isInteger(nr)||nr<1||nr>board.length)return alert(`Enter a rank from 1 to ${board.length}.`);if(nr===x.rank)return;const btn=$(`[data-move="${CSS.escape(key)}"]`);const old=btn.textContent;btn.disabled=true;btn.textContent='…';try{const result=await rpc('admin_move_dynasty_player',{p_player_key:key,p_new_rank:nr});await Promise.all([loadBoard(),loadActivity()]);renderRankings();renderPlayers();$('#metricInjuries').textContent=board.filter(v=>!healthy(v.injury_status)).length;alert(`${x.name} moved from #${x.rank} to #${nr}. ${result?.affected??''} board rows updated.`)}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent=old}}
function openEditor(key){const b=board.find(x=>x.player_key===key),p=profileMap.get(key)||{};if(!b)return;$('#editKey').value=key;$('#drawerTitle').textContent=b.name;$('#editName').value=b.name||'';$('#editPosition').value=b.pos||'WR';$('#editTeam').value=b.team||'';$('#editAge').value=b.age??'';$('#editDraft').value=b.draft??'';$('#editCollege').value=b.college||'';$('#editInjury').value=p.injury_status||b.injury_status||'Healthy';$('#editInjuryDate').value=(p.injury_updated||b.injury_updated||'').slice(0,10);$('#editInjuryNote').value=p.injury_note||b.injury_note||'';$('#editOverview').value=p.overall_breakdown||b.overview||'';$('#profileLink').href=`/player/${encodeURIComponent(key)}`;$('#saveStatus').textContent='';$('#drawerBackdrop').classList.remove('hide');$('#playerDrawer').classList.remove('hide')}
function closeEditor(){$('#drawerBackdrop').classList.add('hide');$('#playerDrawer').classList.add('hide')}
async function savePlayer(e){e.preventDefault();const key=$('#editKey').value;if(!key)return;const save=$('#savePlayer');save.disabled=true;$('#saveStatus').textContent='Saving…';const identity={name:$('#editName').value.trim(),position:$('#editPosition').value,team:$('#editTeam').value.trim(),age:n($('#editAge').value),draft_year:n($('#editDraft').value),college:$('#editCollege').value.trim()||null};const profile={player_key:key,overall_breakdown:$('#editOverview').value.trim(),breakdown_basis:'BBB Admin',breakdown_updated:new Date().toISOString().slice(0,10),injury_status:$('#editInjury').value.trim()||'Healthy',injury_note:$('#editInjuryNote').value.trim(),injury_updated:$('#editInjuryDate').value||new Date().toISOString().slice(0,10),review_status:'Reviewed'};try{await rest(`players?player_key=eq.${encodeURIComponent(key)}`,{method:'PATCH',headers:{'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify(identity)});await rest(`player_profiles?on_conflict=player_key`,{method:'POST',headers:{'Content-Type':'application/json','Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(profile)});$('#saveStatus').textContent='Saved ✓';await Promise.all([loadBoard(),loadProfiles(),loadActivity()]);renderRankings();renderPlayers();$('#metricInjuries').textContent=board.filter(v=>!healthy(v.injury_status)).length;$('#drawerTitle').textContent=identity.name}catch(err){$('#saveStatus').textContent=err.message;$('#saveStatus').style.color='#ef8585'}finally{save.disabled=false}}
function page(name){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$$('.admin-page').forEach(p=>p.classList.add('hide'));$(`#page${name[0].toUpperCase()+name.slice(1)}`).classList.remove('hide')}
document.addEventListener('DOMContentLoaded',()=>{
  $$('.auth-tab').forEach(b=>b.onclick=()=>{authMode=b.dataset.authMode;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$('#authSubmit').textContent=authMode==='login'?'SIGN IN':'CREATE ACCOUNT';$('#authPassword').autocomplete=authMode==='login'?'current-password':'new-password';msg('')});
  $('#authForm').onsubmit=async e=>{e.preventDefault();const btn=$('#authSubmit');btn.disabled=true;msg('');try{const email=$('#authEmail').value.trim().toLowerCase(),password=$('#authPassword').value;if(authMode==='login'){const admin=await signIn(email,password);showApp(admin);await loadAll()}else{const r=await signUp(email,password);if(r.confirmed){showApp(r.admin);await loadAll()}else msg('Account created. Check your email to confirm it, then come back and Sign In.',true)}}catch(err){msg(err.message)}finally{btn.disabled=false}};
  $('#signOut').onclick=()=>{clearSession();location.reload()};
  $$('.nav-btn').forEach(b=>b.onclick=()=>page(b.dataset.page));
  $$('[data-refresh]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await loadAll()}finally{b.disabled=false}});
  ['#rankSearch','#rankPos','#rankMarket'].forEach(s=>$(s).addEventListener(s==='#rankSearch'?'input':'change',()=>{rankPage=0;renderRankings()}));
  $('#rankClear').onclick=()=>{$('#rankSearch').value='';$('#rankPos').value='ALL';$('#rankMarket').value='ALL';rankPage=0;renderRankings()};
  $('#rankPrev').onclick=()=>{rankPage=Math.max(0,rankPage-1);renderRankings()};$('#rankNext').onclick=()=>{rankPage++;renderRankings()};
  ['#playerAdminSearch','#playerAdminPos','#playerAdminInjury'].forEach(s=>$(s).addEventListener(s==='#playerAdminSearch'?'input':'change',()=>{playerPage=0;renderPlayers()}));
  $('#playerAdminClear').onclick=()=>{$('#playerAdminSearch').value='';$('#playerAdminPos').value='ALL';$('#playerAdminInjury').value='ALL';playerPage=0;renderPlayers()};
  $('#playerAdminPrev').onclick=()=>{playerPage=Math.max(0,playerPage-1);renderPlayers()};$('#playerAdminNext').onclick=()=>{playerPage++;renderPlayers()};
  $('#drawerClose').onclick=closeEditor;$('#drawerBackdrop').onclick=closeEditor;$('#playerForm').onsubmit=savePlayer;
  boot();
});